package temperturestatus.temperturestatus;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Patient implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private String name;

	@org.kie.api.definition.type.Label("Age")
	private int age;

	@org.kie.api.definition.type.Label("Infection")
	private boolean infection;

	@org.kie.api.definition.type.Label("Information")
	private String information;

	@org.kie.api.definition.type.Label(value = "HealthCondition")
	private String healthCondition;

	@org.kie.api.definition.type.Label(value = "MedicalEmergency")
	private boolean medicalEmergency;

	public Patient() {
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public boolean getInfection() {
		return this.infection;
	}

	public void setInfection(boolean infection) {
		this.infection = infection;
	}

	public String getInformation() {
		return this.information;
	}

	public void setInformation(String information) {
		this.information = information;
	}

	public String getHealthCondition() {
		return this.healthCondition;
	}

	public void setHealthCondition(String healthCondition) {
		this.healthCondition = healthCondition;
	}

	public boolean getMedicalEmergency() {
		return this.medicalEmergency;
	}

	public void setMedicalEmergency(boolean medicalEmergency) {
		this.medicalEmergency = medicalEmergency;
	}

	public Patient(String name, int age,
			boolean infection, String information,
			String healthCondition, boolean medicalEmergency) {
		super();
		this.name = name;
		this.age = age;
		this.infection = infection;
		this.information = information;
		this.healthCondition = healthCondition;
		this.medicalEmergency = medicalEmergency;
	}

	@Override
	public String toString() {
		return String.format("Patient [name=%s, age=%s, infection=%s, information=%s, healthCondition=%s, medicalEmergency=%s]", name, age,	infection, information, healthCondition, medicalEmergency);
	}

}