package temperturestatus.temperturestatus;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ThermoReading implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "TempReading")
	private java.lang.Double tempReading;
	@org.kie.api.definition.type.Label(value = "Status")
	private java.lang.String status;

	public ThermoReading() {
	}

	public java.lang.Double getTempReading() {
		return this.tempReading;
	}

	public void setTempReading(java.lang.Double tempReading) {
		this.tempReading = tempReading;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public ThermoReading(java.lang.Double tempReading, java.lang.String status) {
		this.tempReading = tempReading;
		this.status = status;
	}

}